export const APIFORMKEY_DASHBOARD = "APIFORMKEY_DASHBOARD";
export const APIFORMKEY_DASHBOARD_SUCCESS = "APIFORMKEY_SUCCESS_DASHBOARD";
export const APIFORMKEY_DASHBOARD_ERROR = "APIFORMKEY_ERROR_DASHBOARD";
